services:
  discovery-service:
    build: ./DiscoveryService
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f","http://192.168.99.100:8761/actuator/health" ]
      interval: 10s
      retries: 8
  config-service:
    build: ./Config-Service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f","http://192.168.99.100:9999/actuator/health" ]
      interval: 10s
      retries: 8
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
  achteur-service:
    build: ./Achteur-Service
    container_name: achteur-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    healthcheck:
      test: [ "CMD", "curl", "-f","http://192.168.99.100:8084/actuator/health" ]
      interval: 20s
      retries: 8
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      config-service:
        condition: service_healthy
  produit-service:
    build: ./Produit-Service
    container_name: produit-service
    ports:
      - '8085:8085'
    expose:
      - '8085'
    healthcheck:
      test: [ "CMD", "curl", "-f","http://192.168.99.100:8085/actuator/health" ]
      interval: 20s
      retries: 8
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      achteur-service:
        condition: service_healthy
  vente-service:
    build: ./Vente-Service
    container_name: vente-service
    ports:
      - '8086:8086'
    expose:
      - '8086'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      produit-service:
        condition: service_healthy
  gateway-service:
    build: ./Gateway-Service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      config-service:
        condition: service_healthy

