spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri:
            http://localhost:8084/
          predicates:
            - Path= /achteurs/**
        - id: r2
          uri:
            http://localhost:8085/
          predicates:
            - Path= /produits/**
        - id: r3
          uri:
            http://localhost:8086/
          predicates:
            - Path= /ventes/**

